/**
 * Shared page chrome (nav, footer, cookie notice, scripts) for every storefront page.
 * Used by scripts/generate-products.js for product pages and by
 * scripts/build-partials.js to refresh index.html and contact.html.
 * Edit the nav or footer here, then run: node scripts/build-partials.js
 */

const ARROW = '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 12h14M13 6l6 6-6 6"/></svg>';
const HEART = '<path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"/>';
const USER = '<path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"/><circle cx="12" cy="7" r="4"/>';

const FONTS_HREF = 'https://fonts.googleapis.com/css2?family=Cinzel:wght@500..700&family=Fraunces:ital,opsz,wght,SOFT,WONK@0,9..144,400..600,0,0;1,9..144,400..600,0,1&family=Manrope:wght@400..800&display=swap';

function headAssets() {
  return `    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preconnect" href="https://res.cloudinary.com" crossorigin>
    <link rel="preconnect" href="https://mantraaq-backend.onrender.com" crossorigin>
    <link href="${FONTS_HREF}" rel="stylesheet">
    <link rel="stylesheet" href="/css/site.css">
    <meta name="theme-color" content="#f3ecdb">
    <link rel="icon" type="image/png" sizes="32x32" href="/assets/images/favicon-32x32.png?v=2">
    <link rel="icon" type="image/x-icon" href="/assets/images/favicon.ico?v=2">
    <link rel="apple-touch-icon" sizes="180x180" href="/assets/images/apple-touch-icon.png?v=2">
    <link rel="manifest" href="/assets/images/site.webmanifest?v=2">`;
}

function gtag() {
  return `    <script async src="https://www.googletagmanager.com/gtag/js?id=G-2EGQB9RZHD"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'G-2EGQB9RZHD');
    </script>`;
}

/**
 * Navigation. ids/classes/data-action hooks are used by main.js, cart.js, auth.js,
 * search.js and wishlist.js, so keep them when restyling.
 * opts.home: true on the homepage (in-page anchors with smooth scroll).
 */
function nav(opts = {}) {
  const h = opts.home ? '' : '/';
  const d = opts.home ? ' data-nav' : '';
  const dm = opts.home ? ' data-nav-mob' : '';
  const strip = ['Free shipping on orders above ₹499', 'Dispatched in 1–2 business days', 'Wetland grown', 'Rooted in Bihar'];
  const stripHtml = strip.map(t => `<span>${t}</span>`).join('');
  return `<!-- NAV_START: generated by scripts/partials.js -->
<nav class="nav-bar" id="mainNav" role="navigation" aria-label="Main navigation">
  <div class="nav-strip" aria-label="Store highlights">
    <div class="nav-strip-track" aria-hidden="true">${stripHtml}${stripHtml}</div>
    <span class="sr-only">Free shipping on orders above ₹499. Dispatched in 1 to 2 business days.</span>
  </div>
  <div class="nav-inner">
    <a href="/" class="nav-logo" id="navLogoLink" aria-label="MantraAQ home">
      <span class="nav-logo-img-wrap"><img src="/assets/images/brand/logo-maroon-128.webp" alt="" class="nav-logo-img" id="navLogoImg" width="36" height="36"></span>
      <span class="nav-logo-text">MantraAQ</span>
    </a>
    <div class="nav-links" id="navLinks">
      <a href="${h}#products" class="nav-link"${d}>Shop</a>
      <a href="${h}#story" class="nav-link"${d}>Our story</a>
      <a href="${h}#recipes" class="nav-link"${d}>Recipes</a>
      <a href="/faq" class="nav-link">FAQ</a>
      <a href="/contact" class="nav-link">Contact</a>
    </div>
    <div class="nav-actions">
      <a data-action="search" href="#" class="nav-action" title="Search products" aria-label="Search products">
        <svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="7.5"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg>
        <span class="nav-action-label">Search</span>
      </a>
      <a data-action="wishlist" href="#" class="nav-action nav-account" title="Wishlist" aria-label="Wishlist">
        <svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">${HEART}</svg>
        <span class="nav-action-label">Wishlist</span>
      </a>
      <a data-action="account" href="#" class="nav-action nav-account" title="Account" aria-label="Account">
        <svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">${USER}</svg>
        <span class="nav-action-label">Account</span>
      </a>
      <a data-action="cart" href="#" class="nav-action nav-cart" title="Cart" aria-label="Cart">
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M6 7h12l-1 13H7L6 7z"/><path d="M9 7a3 3 0 016 0"/></svg>
        <span>Cart</span>
      </a>
      <button class="nav-hamburger" id="navHamburger" aria-label="Open menu" aria-expanded="false" aria-controls="navDrawer" type="button">
        <span class="nav-ham-bar"></span><span class="nav-ham-bar"></span><span class="nav-ham-bar"></span>
      </button>
    </div>
  </div>
  <div class="nav-drawer" id="navDrawer" inert>
    <div class="nav-drawer-inner">
      <a href="${h}#products" class="nav-drawer-link"${dm}>Shop</a>
      <a href="${h}#story" class="nav-drawer-link"${dm}>Our story</a>
      <a href="${h}#recipes" class="nav-drawer-link"${dm}>Recipes</a>
      <a href="/faq" class="nav-drawer-link">FAQ</a>
      <a href="/contact" class="nav-drawer-link">Contact</a>
      <div class="nav-drawer-divider"></div>
      <a data-action="wishlist" href="#" class="nav-drawer-link"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">${HEART}</svg>Wishlist</a>
      <a data-action="account" href="#" class="nav-drawer-link nav-drawer-account"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">${USER}</svg>My account</a>
      <a data-action="cart" href="#" class="nav-drawer-cart">View cart</a>
    </div>
  </div>
</nav>
<!-- NAV_END -->`;
}

function footer() {
  return `<!-- FOOTER_START: generated by scripts/partials.js -->
<div class="ornament" aria-hidden="true"></div>
<footer class="foot" id="footer">
  <div class="wrap">
    <div class="foot-top">
      <div class="foot-brand">
        <a href="/" class="foot-logo"><img src="/assets/images/brand/logo-cream-128.webp" alt="" width="40" height="40">MantraAQ</a>
        <p><em class="foot-tagline">Eat. Heal. Feel.</em><br>Singhara foods from the wetlands of Bihar, made with 200+ farmer families. MantraAQ Industries Private Limited, Begusarai.</p>
        <div class="foot-socials">
          <a href="https://instagram.com/mantraaq" target="_blank" rel="noopener" aria-label="Instagram"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="2" y="2" width="20" height="20" rx="5"/><path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37z"/><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"/></svg></a>
          <a href="https://linkedin.com/company/mantraaq" target="_blank" rel="noopener" aria-label="LinkedIn"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-4 0v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"/><circle cx="4" cy="4" r="2"/></svg></a>
          <a href="https://wa.me/918283816755" target="_blank" rel="noopener" aria-label="WhatsApp"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M21 11.5a8.4 8.4 0 01-12.4 7.4L3 21l1.9-5.7A8.5 8.5 0 1121 11.5z"/></svg></a>
        </div>
      </div>
      <div>
        <h4>Shop</h4>
        <ul>
          <li><a href="/products/singhara-atta">Singhara Atta</a></li>
          <li><a href="/products/singhara-pasta">Singhara Macaroni</a></li>
          <li><a href="/products/singhara-vermicell">Singhara Vermicelli</a></li>
          <li><a href="/products/dry-singhara">Dry Singhara</a></li>
          <li><a href="/products/fresh-singhara">Fresh Singhara</a></li>
        </ul>
      </div>
      <div>
        <h4>Help</h4>
        <ul>
          <li><a href="/faq">FAQ</a></li>
          <li><a href="/shipping-policy">Shipping</a></li>
          <li><a href="/refund-policy">Refunds &amp; replacements</a></li>
          <li><a href="/contact">Contact us</a></li>
          <li><a href="#" data-action="account">Track your order</a></li>
        </ul>
      </div>
      <div>
        <h4>Get in touch</h4>
        <ul>
          <li><a href="mailto:hello@mantraaq.com">hello@mantraaq.com</a></li>
          <li><a href="tel:+918283816755">+91 82838 16755</a></li>
          <li>Begusarai, Bihar, India</li>
          <li><a href="/privacy-policy">Privacy policy</a></li>
          <li><a href="/terms-and-conditions">Terms &amp; conditions</a></li>
        </ul>
      </div>
    </div>
    <div class="foot-word" aria-hidden="true">MantraAQ</div>
    <div class="foot-bottom">
      <span>© 2026 MantraAQ Industries Private Limited. FSSAI Lic. No. 20426155000003</span>
      <span>Wetland grown ❖ Rooted in Bihar</span>
    </div>
  </div>
</footer>

<div id="maq-cookie-banner" class="cookie" role="dialog" aria-label="Cookie notice" hidden>
  We use cookies and analytics to improve your experience. See our <a href="/privacy-policy">privacy policy</a>.
  <div class="cookie-actions">
    <button type="button" class="btn btn--light" data-cookie-close>Accept</button>
    <button type="button" class="btn btn--ghost" data-cookie-close>Dismiss</button>
  </div>
</div>
<!-- FOOTER_END -->`;
}

/** Script tags. Order matters: api → cart → auth → product-card → storefront → search → wishlist → main. */
function scripts(extra = []) {
  const core = [
    'https://cdnjs.cloudflare.com/ajax/libs/dompurify/3.0.8/purify.min.js',
    '/js/sanitize.js', '/js/toast.js', '/js/api.js', '/js/cart.js', '/js/auth.js',
    '/js/product-card.js', '/js/storefront.js', '/js/search.js', '/js/wishlist.js', '/js/main.js'
  ];
  const deferred = ['/js/vendor/gsap.min.js', '/js/vendor/ScrollTrigger.min.js', '/js/site.js', ...extra];
  return [
    ...core.map(src => `<script src="${src}"></script>`),
    ...deferred.map(src => `<script src="${src}" defer></script>`)
  ].join('\n');
}

module.exports = { nav, footer, scripts, headAssets, gtag, ARROW, FONTS_HREF };
